inherit_from:
  - .rubocop_airbnb.yml
AllCops:
  TargetRubyVersion: 2.7.2
  TargetRailsVersion: 6.0.3

  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
